[package]
name = "product_graph_rs"
version = "0.1.0"
authors = ["Cameron Rodgers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]



[dependencies]
rand = "0.7"
rayon = "1.3.0"
