name: Rust

on:
  push:
    branches: [ master, rust_library ]
  pull_request:
    branches: [ master, rust_library ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: production_graph_rs
    - name: Run tests
      run: cargo test --verbose
      working-directory: production_graph_rs
    - name: Formatting
      run: |
        rustup component add rustfmt 
        cargo fmt -- --check
      working-directory: production_graph_rs
